version: '3.8'
services:
  flask_app:
    image: flask-api:latest
    ports:
      - "42069:42069"
    environment:
      - FLASK_ENV=development

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - flask_app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

